name: BlockShufflePlugin
author: SulphurousC
description: An implementation of the BlockShuffle minigame
commands:
  blockshuffle:
    description: BlockShuffle Main Command
    usage: "Usage : /blockshuffle [start][stop][info][add][remove][list][set [noOfRounds][RoundTime][foodAmount]]"
version: 2.1
main: com.sulphurouscerebrum.plugins.Main
